apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system
  labels:
    name: solar-system
    app: solar-system-app
spec:
  selector:
    matchLabels:
      name: solar-system
      app: solar-system-app
  replicas: 1
  template:
    metadata:
      name: solar-system
      labels:
        name: solar-system
        app: solar-system-app
    spec:
      containers:
        - name: solar-system
          image: siddharth67/solar-system:v9
          ports:
            - containerPort: 80


