apiVersion: v1
kind: Service
metadata:
  labels:
    app: bode-be
  name: solar-system-service
spec:
  ports:
  - port: 80 #change to 80
    protocol: TCP
    targetPort: 80 #change to 80
  selector:
    app: bode-be
  type: NodePort
